name: deploy to github pages

on:
  push:
    branches: [master]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    # Checkout the code
    - uses: actions/setup-dotnet@v3
    # Install .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
     # Install dotnet wasm buildtools workload
    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools
         # Install Node JS
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1
      with:
          node-version: '16.13.0'
    - run: npm install
    # Restore Dependencies
    - name: Restore dependencies
      run: dotnet restore
    # Build Project
    - name: Build
      run: dotnet build ./Milton.Student.Client.sln --configuration Release --no-restore
    # Publishes Blazor project to the release-folder
    - name: Publish with dotnet
      run: dotnet publish Milton.Blazor.App/Milton.Blazor.App.csproj -c:Release -p:GHPages=true --no-restore -o dist/Web --nologo
    # Change baseurl
    - name: Change base-tag in index.html from / to Milton.Student.Client
      run: sed -i 's/<base href="\/" \/>/<base href="\/Milton.Student.Client\/" \/>/g' dist/Web/wwwroot/index.html  
   # Commit
    - name: Commit wwwroot to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/Web/wwwroot # The folder the action should deploy.
        SINGLE_COMMIT: true
